#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /*
     * ┌───┬───┬───┬───┐
     * │ 7 │ 8 │ 9 │DEL│
     * ├───┼───┼───┼───┤
     * │ 4 │ 5 │ 6 │BCK│
     * ├───┼───┼───┼───┤
     * │ 1 │ 2 │ 3 │GUI│
     * ├───┼───┼───┼───┤
     * │FN1│ 0 │ . │RET│
     * └───┴───┴───┴───┘
     */
        [0] = LAYOUT(   KC_P7,  KC_P8,  KC_P9,      KC_DEL,
                        KC_P4,  KC_P5,  KC_P6,      KC_BSPC,
                        KC_P1,  KC_P2,  KC_P3,      KC_RGUI,
                        MO(1),  KC_P0,  KC_PDOT,    KC_PENT),
    /*
     * ┌───┬───┬───┬───┐
     * │PUP│ HM│END│NLK│
     * ├───┼───┼───┼───┤
     * │PDN│ Up│ 6 │---│
     * ├───┼───┼───┼───┤
     * │Lft│Dwn│Rgt│---│
     * ├───┼───┼───┼───┤
     * │---│PSc│FN2│---│
     * └───┴───┴───┴───┘
     */
        [1] = LAYOUT(   KC_PGUP,    KC_HOME,    KC_END,     KC_NUM,
                        KC_PGDN,    KC_UP,      KC_TRNS,    KC_TRNS,
                        KC_LEFT,    KC_DOWN,    KC_RGHT,    KC_TRNS,
                        KC_TRNS,    KC_PSCR,    MO(2),      KC_TRNS),
        [2] = LAYOUT(   QK_BOOT,    KC_TRNS,    KC_TRNS,    KC_TRNS,
                        KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,
                        KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,
                        KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS)
};

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
        [0] = { ENCODER_CCW_CW(KC_P1, KC_P2),       ENCODER_CCW_CW(KC_VOLD, KC_VOLU)    },
        [1] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU),   ENCODER_CCW_CW(KC_VOLD, KC_VOLU)    },
        [2] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU),   ENCODER_CCW_CW(KC_VOLD, KC_VOLU)    },
};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
